name: Docker-compose

on: [pull_request]

jobs:
  Unit-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Running Unit Tests
        run: |
          docker compose up
          docker compose run test

          

    