name: Docker-compose

on: [pull_request]

jobs:
  Unit-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Running Unit Tests
        run: |
          docker compose run test 

          

    
