name: Docker-compose

on: [pull_request]

jobs:
  Unit-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Running Unit Tests
        run: |
          docker-compose -f "docker-compose.yml" up
          docker-compose run test

          

    